// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/configurazione/BarMatrix.tsx": () => import("../components/mockups/configurazione/BarMatrix.tsx"),
  "./components/mockups/configurazione/InspectEdit.tsx": () => import("../components/mockups/configurazione/InspectEdit.tsx"),
  "./components/mockups/configurazione/ParameterAccordion.tsx": () => import("../components/mockups/configurazione/ParameterAccordion.tsx"),
  "./components/mockups/configurazione/ProfileCard.tsx": () => import("../components/mockups/configurazione/ProfileCard.tsx")
};
