import type { IngredientDefinition } from './types'

export const DEFAULT_INGREDIENTS: IngredientDefinition[] = [
  // LATTICINI & UOVA
  { id: 'latte-intero', nome: 'Latte intero', group: 'latticiniUova', acquaPct: 87.2, grassiPct: 3.5, slngPct: 8.7, zuccheri: { lattosio: 4.8 }, altriSolidiPct: 0.6, isReadOnly: true },
  { id: 'latte-parz-scremato', nome: 'Latte parz. scremato', group: 'latticiniUova', acquaPct: 89.0, grassiPct: 1.6, slngPct: 8.9, zuccheri: { lattosio: 4.8 }, altriSolidiPct: 0.5, isReadOnly: true },
  { id: 'latte-scremato', nome: 'Latte scremato', group: 'latticiniUova', acquaPct: 90.5, grassiPct: 0.1, slngPct: 9.0, zuccheri: { lattosio: 4.9 }, altriSolidiPct: 0.5, isReadOnly: true },
  { id: 'panna-35', nome: 'Panna 35%', group: 'latticiniUova', acquaPct: 59.5, grassiPct: 35.0, slngPct: 5.0, zuccheri: { lattosio: 2.9 }, altriSolidiPct: 0.6, isReadOnly: true },
  { id: 'panna-38', nome: 'Panna 38%', group: 'latticiniUova', acquaPct: 57.0, grassiPct: 38.0, slngPct: 5.0, zuccheri: { lattosio: 2.7 }, altriSolidiPct: 0.3, isReadOnly: true },
  { id: 'burro', nome: 'Burro', group: 'latticiniUova', acquaPct: 15.8, grassiPct: 82.0, slngPct: 1.2, zuccheri: {}, altriSolidiPct: 1.0, isReadOnly: true },
  { id: 'lps', nome: 'Latte in polvere scremato (LPS)', group: 'latticiniUova', acquaPct: 3.5, grassiPct: 0.8, slngPct: 95.0, zuccheri: { lattosio: 50.5 }, altriSolidiPct: 0.7, isReadOnly: true },
  { id: 'lpi', nome: 'Latte in polvere intero (LPI)', group: 'latticiniUova', acquaPct: 3.0, grassiPct: 26.0, slngPct: 70.0, zuccheri: { lattosio: 36.5 }, altriSolidiPct: 1.0, isReadOnly: true },
  { id: 'tuorlo', nome: "Tuorlo d'uovo fresco", group: 'latticiniUova', acquaPct: 51.0, grassiPct: 31.0, slngPct: 0.0, zuccheri: {}, altriSolidiPct: 18.0, isReadOnly: true },
  { id: 'albume', nome: "Albume d'uovo fresco", group: 'latticiniUova', acquaPct: 88.0, grassiPct: 0.0, slngPct: 0.0, zuccheri: {}, altriSolidiPct: 12.0, isReadOnly: true },
  { id: 'ricotta', nome: 'Ricotta intera', group: 'latticiniUova', acquaPct: 71.0, grassiPct: 12.0, slngPct: 8.0, zuccheri: { lattosio: 3.0 }, altriSolidiPct: 6.0, isReadOnly: true },
  { id: 'mascarpone', nome: 'Mascarpone', group: 'latticiniUova', acquaPct: 44.0, grassiPct: 44.0, slngPct: 5.5, zuccheri: { lattosio: 2.5 }, altriSolidiPct: 4.0, isReadOnly: true },
  { id: 'yogurt', nome: 'Yogurt intero', group: 'latticiniUova', acquaPct: 85.0, grassiPct: 3.5, slngPct: 7.5, zuccheri: { lattosio: 4.0 }, altriSolidiPct: 0.0, isReadOnly: true },
  { id: 'formaggio-fresco', nome: 'Formaggio fresco spalmabile', group: 'latticiniUova', acquaPct: 54.0, grassiPct: 34.0, slngPct: 6.5, zuccheri: { lattosio: 2.7 }, altriSolidiPct: 2.8, isReadOnly: true },
  { id: 'latte-condensato', nome: 'Latte condensato zuccherato', group: 'latticiniUova', acquaPct: 26.0, grassiPct: 8.5, slngPct: 17.0, zuccheri: { saccarosio: 44.0 }, altriSolidiPct: 4.5, isReadOnly: true },
  { id: 'panna-polvere', nome: 'Panna in polvere', group: 'latticiniUova', acquaPct: 3.0, grassiPct: 42.0, slngPct: 46.0, zuccheri: { lattosio: 25.0 }, altriSolidiPct: 9.0, isReadOnly: true },

  // ZUCCHERI
  { id: 'saccarosio', nome: 'Saccarosio', group: 'zuccheri', acquaPct: 0, grassiPct: 0, slngPct: 0, zuccheri: { saccarosio: 100 }, altriSolidiPct: 0, minPct: 8, maxPct: 15, isReadOnly: true },
  { id: 'destrosio', nome: 'Destrosio (Glucosio)', group: 'zuccheri', acquaPct: 0, grassiPct: 0, slngPct: 0, zuccheri: { destrosio: 100 }, altriSolidiPct: 0, isReadOnly: true },
  { id: 'fruttosio', nome: 'Fruttosio', group: 'zuccheri', acquaPct: 0, grassiPct: 0, slngPct: 0, zuccheri: { fruttosio: 100 }, altriSolidiPct: 0, isReadOnly: true },
  { id: 'zucchero-invertito', nome: 'Zucchero Invertito', group: 'zuccheri', acquaPct: 23, grassiPct: 0, slngPct: 0, zuccheri: { invertito: 75 }, altriSolidiPct: 2, isReadOnly: true },
  { id: 'miele', nome: 'Miele', group: 'zuccheri', acquaPct: 17, grassiPct: 0, slngPct: 0, zuccheri: { miele: 80 }, altriSolidiPct: 3, isReadOnly: true },
  { id: 'trealosio', nome: 'Trealosio', group: 'zuccheri', acquaPct: 0, grassiPct: 0, slngPct: 0, zuccheri: { trealosio: 100 }, altriSolidiPct: 0, isReadOnly: true },
  { id: 'isofruttosio', nome: 'Isofruttosio', group: 'zuccheri', acquaPct: 0, grassiPct: 0, slngPct: 0, zuccheri: { isofruttosio: 100 }, altriSolidiPct: 0, isReadOnly: true },
  { id: 'maltitolo', nome: 'Maltitolo', group: 'zuccheri', acquaPct: 0, grassiPct: 0, slngPct: 0, zuccheri: { maltitolo: 100 }, altriSolidiPct: 0, isReadOnly: true },
  { id: 'sorbitolo', nome: 'Sorbitolo', group: 'zuccheri', acquaPct: 0, grassiPct: 0, slngPct: 0, zuccheri: { sorbitolo: 100 }, altriSolidiPct: 0, isReadOnly: true },
  { id: 'mannitolo', nome: 'Mannitolo', group: 'zuccheri', acquaPct: 0, grassiPct: 0, slngPct: 0, zuccheri: { mannitolo: 100 }, altriSolidiPct: 0, isReadOnly: true },
  { id: 'xilitolo', nome: 'Xilitolo', group: 'zuccheri', acquaPct: 0, grassiPct: 0, slngPct: 0, zuccheri: { xilitolo: 100 }, altriSolidiPct: 0, isReadOnly: true },
  { id: 'eritritolo', nome: 'Eritritolo', group: 'zuccheri', acquaPct: 0, grassiPct: 0, slngPct: 0, zuccheri: { eritritolo: 100 }, altriSolidiPct: 0, isReadOnly: true },
  { id: 'tagatosio', nome: 'Tagatosio', group: 'zuccheri', acquaPct: 0, grassiPct: 0, slngPct: 0, zuccheri: { tagatosio: 100 }, altriSolidiPct: 0, isReadOnly: true },
  { id: 'stevia', nome: 'Stevia (estratto)', group: 'zuccheri', acquaPct: 0, grassiPct: 0, slngPct: 0, zuccheri: { stevia: 100 }, altriSolidiPct: 0, isReadOnly: true },
  { id: 'glicrizina', nome: 'Glicrizina', group: 'zuccheri', acquaPct: 0, grassiPct: 0, slngPct: 0, zuccheri: { glicrizina: 100 }, altriSolidiPct: 0, isReadOnly: true },
  { id: 'glucosio-at-21de', nome: 'Glucosio Atomizzato 21 DE', group: 'zuccheri', acquaPct: 0, grassiPct: 0, slngPct: 0, zuccheri: { glucosioAt21DE: 100 }, altriSolidiPct: 0, isReadOnly: true },
  { id: 'glucosio-at-39de', nome: 'Glucosio Atomizzato 39 DE', group: 'zuccheri', acquaPct: 0, grassiPct: 0, slngPct: 0, zuccheri: { glucosioAt39DE: 100 }, altriSolidiPct: 0, isReadOnly: true },
  { id: 'glucosio-at-42de', nome: 'Glucosio Atomizzato 42 DE', group: 'zuccheri', acquaPct: 0, grassiPct: 0, slngPct: 0, zuccheri: { glucosioAt42DE: 100 }, altriSolidiPct: 0, isReadOnly: true },
  { id: 'glucosio-at-52de', nome: 'Glucosio Atomizzato 52 DE', group: 'zuccheri', acquaPct: 0, grassiPct: 0, slngPct: 0, zuccheri: { glucosioAt52DE: 100 }, altriSolidiPct: 0, isReadOnly: true },
  { id: 'maltodestrina-5de', nome: 'Maltodestrina 5 DE', group: 'zuccheri', acquaPct: 0, grassiPct: 0, slngPct: 0, zuccheri: { maltodestrina5DE: 100 }, altriSolidiPct: 0, isReadOnly: true },
  { id: 'maltodestrina-18de', nome: 'Maltodestrina 18 DE', group: 'zuccheri', acquaPct: 0, grassiPct: 0, slngPct: 0, zuccheri: { maltodestrina18DE: 100 }, altriSolidiPct: 0, isReadOnly: true },
  { id: 'maltodestrina-20de', nome: 'Maltodestrina 20 DE', group: 'zuccheri', acquaPct: 0, grassiPct: 0, slngPct: 0, zuccheri: { maltodestrina20DE: 100 }, altriSolidiPct: 0, isReadOnly: true },
  { id: 'lattosio-pure', nome: 'Lattosio', group: 'zuccheri', acquaPct: 0, grassiPct: 0, slngPct: 0, zuccheri: { lattosio: 100 }, altriSolidiPct: 0, isReadOnly: true },

  // NEUTRI & BASI
  { id: 'neutro-gelato', nome: 'Neutro per gelato', group: 'neutriBasi', acquaPct: 0, grassiPct: 0, slngPct: 0, zuccheri: {}, altriSolidiPct: 100, minPct: 0.2, maxPct: 0.5, isReadOnly: true },
  { id: 'neutro-sorbetto', nome: 'Neutro per sorbetto', group: 'neutriBasi', acquaPct: 0, grassiPct: 0, slngPct: 0, zuccheri: {}, altriSolidiPct: 100, minPct: 0.2, maxPct: 0.5, isReadOnly: true },
  { id: 'neutro-vegan', nome: 'Neutro per gelato vegan', group: 'neutriBasi', acquaPct: 0, grassiPct: 0, slngPct: 0, zuccheri: {}, altriSolidiPct: 100, minPct: 0.2, maxPct: 0.5, isReadOnly: true },
  { id: 'carrube', nome: 'Farina di semi di carrube', group: 'neutriBasi', acquaPct: 0, grassiPct: 0, slngPct: 0, zuccheri: {}, altriSolidiPct: 100, minPct: 0.1, maxPct: 0.3, isReadOnly: true },
  { id: 'guar', nome: 'Guar', group: 'neutriBasi', acquaPct: 0, grassiPct: 0, slngPct: 0, zuccheri: {}, altriSolidiPct: 100, minPct: 0.05, maxPct: 0.2, isReadOnly: true },
  { id: 'inulina', nome: 'Inulina', group: 'neutriBasi', acquaPct: 0, grassiPct: 0, slngPct: 0, zuccheri: {}, altriSolidiPct: 100, minPct: 0.5, maxPct: 3.0, isReadOnly: true },
  { id: 'carragenina', nome: 'Carragenina', group: 'neutriBasi', acquaPct: 0, grassiPct: 0, slngPct: 0, zuccheri: {}, altriSolidiPct: 100, minPct: 0.02, maxPct: 0.1, isReadOnly: true },
  { id: 'agar-agar', nome: 'Agar agar', group: 'neutriBasi', acquaPct: 0, grassiPct: 0, slngPct: 0, zuccheri: {}, altriSolidiPct: 100, minPct: 0.05, maxPct: 0.3, isReadOnly: true },
  { id: 'pectina', nome: 'Pectina', group: 'neutriBasi', acquaPct: 0, grassiPct: 0, slngPct: 0, zuccheri: {}, altriSolidiPct: 100, minPct: 0.1, maxPct: 0.5, isReadOnly: true },

  // INGREDIENTI PRINCIPALI
  { id: 'cioccolato-fondente-70', nome: 'Cioccolato fondente 70%', group: 'ingredientiPrincipali', acquaPct: 1.0, grassiPct: 42.0, slngPct: 0.0, zuccheri: { saccarosio: 28.0 }, altriSolidiPct: 28.0, isReadOnly: true },
  { id: 'cioccolato-fondente-56', nome: 'Cioccolato fondente 56%', group: 'ingredientiPrincipali', acquaPct: 1.0, grassiPct: 33.0, slngPct: 0.0, zuccheri: { saccarosio: 40.0 }, altriSolidiPct: 25.0, isReadOnly: true },
  { id: 'cioccolato-latte', nome: 'Cioccolato al latte', group: 'ingredientiPrincipali', acquaPct: 1.5, grassiPct: 31.0, slngPct: 6.5, zuccheri: { saccarosio: 45.0 }, altriSolidiPct: 16.0, isReadOnly: true },
  { id: 'cacao-polvere', nome: 'Cacao in polvere 22-24%', group: 'ingredientiPrincipali', acquaPct: 3.0, grassiPct: 22.0, slngPct: 0.0, zuccheri: {}, altriSolidiPct: 74.0, isReadOnly: true },
  { id: 'pasta-pistacchio', nome: 'Pasta di pistacchio', group: 'ingredientiPrincipali', acquaPct: 4.0, grassiPct: 49.0, slngPct: 0.0, zuccheri: { saccarosio: 6.0 }, altriSolidiPct: 41.0, isReadOnly: true },
  { id: 'pasta-nocciola', nome: 'Pasta di nocciola', group: 'ingredientiPrincipali', acquaPct: 2.0, grassiPct: 62.0, slngPct: 0.0, zuccheri: { saccarosio: 4.0 }, altriSolidiPct: 31.0, isReadOnly: true },
  { id: 'pasta-mandorla', nome: 'Pasta di mandorla', group: 'ingredientiPrincipali', acquaPct: 4.0, grassiPct: 52.0, slngPct: 0.0, zuccheri: { saccarosio: 5.0 }, altriSolidiPct: 38.0, isReadOnly: true },
  { id: 'pasta-caffe', nome: 'Pasta di caffè', group: 'ingredientiPrincipali', acquaPct: 3.0, grassiPct: 15.0, slngPct: 0.0, zuccheri: {}, altriSolidiPct: 82.0, isReadOnly: true },
  { id: 'vaniglia', nome: 'Estratto di vaniglia', group: 'ingredientiPrincipali', acquaPct: 50.0, grassiPct: 0.0, slngPct: 0.0, zuccheri: {}, altriSolidiPct: 50.0, isReadOnly: true },
  { id: 'torrone', nome: 'Torrone granulato', group: 'ingredientiPrincipali', acquaPct: 3.0, grassiPct: 20.0, slngPct: 3.0, zuccheri: { saccarosio: 45.0 }, altriSolidiPct: 29.0, isReadOnly: true },
  { id: 'lemon-curd', nome: 'Lemon curd', group: 'ingredientiPrincipali', acquaPct: 28.0, grassiPct: 10.0, slngPct: 2.0, zuccheri: { saccarosio: 50.0 }, altriSolidiPct: 10.0, isReadOnly: true },
  { id: 'crema-marroni', nome: 'Crema di marroni', group: 'ingredientiPrincipali', acquaPct: 20.0, grassiPct: 2.0, slngPct: 0.0, zuccheri: { saccarosio: 52.0 }, altriSolidiPct: 26.0, isReadOnly: true },

  // FRUTTA & VERDURA
  { id: 'fragola', nome: 'Fragola fresca/purea', group: 'fruttaVerdura', acquaPct: 90.0, grassiPct: 0.0, slngPct: 0.0, zuccheri: { fruttosio: 3.5, saccarosio: 2.0 }, altriSolidiPct: 4.5, isReadOnly: true },
  { id: 'limone', nome: 'Limone succo', group: 'fruttaVerdura', acquaPct: 91.0, grassiPct: 0.0, slngPct: 0.0, zuccheri: { fruttosio: 1.0, saccarosio: 0.5 }, altriSolidiPct: 7.5, isReadOnly: true },
  { id: 'mango', nome: 'Mango purea', group: 'fruttaVerdura', acquaPct: 83.0, grassiPct: 0.0, slngPct: 0.0, zuccheri: { fruttosio: 6.0, saccarosio: 6.5 }, altriSolidiPct: 4.5, isReadOnly: true },
  { id: 'lampone', nome: 'Lampone purea', group: 'fruttaVerdura', acquaPct: 87.0, grassiPct: 0.0, slngPct: 0.0, zuccheri: { fruttosio: 4.5, saccarosio: 2.0 }, altriSolidiPct: 6.5, isReadOnly: true },
  { id: 'passion', nome: 'Frutto della passione purea', group: 'fruttaVerdura', acquaPct: 85.0, grassiPct: 0.0, slngPct: 0.0, zuccheri: { fruttosio: 6.0, saccarosio: 3.5 }, altriSolidiPct: 5.5, isReadOnly: true },
  { id: 'banana', nome: 'Banana', group: 'fruttaVerdura', acquaPct: 75.0, grassiPct: 0.3, slngPct: 0.0, zuccheri: { fruttosio: 4.9, saccarosio: 6.5 }, altriSolidiPct: 13.3, isReadOnly: true },
  { id: 'pera', nome: 'Pera purea', group: 'fruttaVerdura', acquaPct: 84.0, grassiPct: 0.0, slngPct: 0.0, zuccheri: { fruttosio: 6.0, saccarosio: 1.0 }, altriSolidiPct: 9.0, isReadOnly: true },
  { id: 'pesca', nome: 'Pesca purea', group: 'fruttaVerdura', acquaPct: 86.0, grassiPct: 0.0, slngPct: 0.0, zuccheri: { fruttosio: 2.0, saccarosio: 4.8 }, altriSolidiPct: 7.2, isReadOnly: true },
  { id: 'arancia', nome: 'Arancia succo', group: 'fruttaVerdura', acquaPct: 88.0, grassiPct: 0.0, slngPct: 0.0, zuccheri: { fruttosio: 2.5, saccarosio: 4.2 }, altriSolidiPct: 5.3, isReadOnly: true },
  { id: 'ananas', nome: 'Ananas purea', group: 'fruttaVerdura', acquaPct: 86.0, grassiPct: 0.0, slngPct: 0.0, zuccheri: { fruttosio: 2.5, saccarosio: 4.0 }, altriSolidiPct: 7.5, isReadOnly: true },
  { id: 'cocco', nome: 'Cocco purea', group: 'fruttaVerdura', acquaPct: 58.0, grassiPct: 22.0, slngPct: 0.0, zuccheri: { saccarosio: 4.5 }, altriSolidiPct: 15.5, isReadOnly: true },
  { id: 'fico', nome: 'Fico purea', group: 'fruttaVerdura', acquaPct: 79.0, grassiPct: 0.0, slngPct: 0.0, zuccheri: { fruttosio: 10.0, saccarosio: 2.0 }, altriSolidiPct: 9.0, isReadOnly: true },
  { id: 'melone', nome: 'Melone purea', group: 'fruttaVerdura', acquaPct: 90.0, grassiPct: 0.0, slngPct: 0.0, zuccheri: { fruttosio: 3.0, saccarosio: 3.5 }, altriSolidiPct: 3.5, isReadOnly: true },
  { id: 'albicocca', nome: 'Albicocca purea', group: 'fruttaVerdura', acquaPct: 86.0, grassiPct: 0.0, slngPct: 0.0, zuccheri: { fruttosio: 2.4, saccarosio: 4.0 }, altriSolidiPct: 7.6, isReadOnly: true },
  { id: 'mora', nome: 'Mora purea', group: 'fruttaVerdura', acquaPct: 88.0, grassiPct: 0.0, slngPct: 0.0, zuccheri: { fruttosio: 3.5, saccarosio: 0.5 }, altriSolidiPct: 8.0, isReadOnly: true },
  { id: 'ribes-nero', nome: 'Ribes nero purea', group: 'fruttaVerdura', acquaPct: 80.0, grassiPct: 0.0, slngPct: 0.0, zuccheri: { fruttosio: 4.0, saccarosio: 3.0 }, altriSolidiPct: 13.0, isReadOnly: true },
  { id: 'mirtillo', nome: 'Mirtillo purea', group: 'fruttaVerdura', acquaPct: 86.0, grassiPct: 0.0, slngPct: 0.0, zuccheri: { fruttosio: 4.3, saccarosio: 2.7 }, altriSolidiPct: 7.0, isReadOnly: true },
  { id: 'kiwi', nome: 'Kiwi purea', group: 'fruttaVerdura', acquaPct: 84.0, grassiPct: 0.5, slngPct: 0.0, zuccheri: { fruttosio: 4.5, saccarosio: 4.0 }, altriSolidiPct: 7.0, isReadOnly: true },
  { id: 'melograno', nome: 'Melograno succo', group: 'fruttaVerdura', acquaPct: 85.0, grassiPct: 0.0, slngPct: 0.0, zuccheri: { fruttosio: 4.7, saccarosio: 5.0 }, altriSolidiPct: 5.3, isReadOnly: true },

  // ALCOLICI (placeholder ingredients)
  { id: 'vodka', nome: 'Vodka 40%', group: 'alcolici', acquaPct: 60, grassiPct: 0, slngPct: 0, zuccheri: {}, altriSolidiPct: 0, isReadOnly: true },
  { id: 'rum', nome: 'Rum 40%', group: 'alcolici', acquaPct: 60, grassiPct: 0, slngPct: 0, zuccheri: {}, altriSolidiPct: 0, isReadOnly: true },
  { id: 'limoncello', nome: 'Limoncello', group: 'alcolici', acquaPct: 55, grassiPct: 0, slngPct: 0, zuccheri: { saccarosio: 30 }, altriSolidiPct: 0, isReadOnly: true },

  // ALIMENTI TRITATI
  { id: 'nocciole-tritate', nome: 'Nocciole tritate', group: 'alimentiTritati', acquaPct: 5, grassiPct: 62, slngPct: 0, zuccheri: { saccarosio: 4 }, altriSolidiPct: 29, isReadOnly: true },
  { id: 'gocce-cioccolato', nome: 'Gocce di cioccolato', group: 'alimentiTritati', acquaPct: 1, grassiPct: 33, slngPct: 0, zuccheri: { saccarosio: 40 }, altriSolidiPct: 25, isReadOnly: true },
  { id: 'biscotto-tritato', nome: 'Biscotto tritato', group: 'alimentiTritati', acquaPct: 3, grassiPct: 20, slngPct: 2, zuccheri: { saccarosio: 25 }, altriSolidiPct: 50, isReadOnly: true },
  { id: 'pistacchi-tritati', nome: 'Pistacchi tritati', group: 'alimentiTritati', acquaPct: 4, grassiPct: 45, slngPct: 0, zuccheri: { saccarosio: 8 }, altriSolidiPct: 43, isReadOnly: true },
]
